### ISSUE TITLE
Unhandled exception in /sbin/mount.efs after reboot - multiple Access Point mounts fail 

### ISSUE THREAD

**Issue by dale-c-anderson** [aws/efs-utils#105]
I'm mounting an efs file system (for visibility by admins), and 3 access points on that efs instance (for the application):
```
# /etc/fstab

LABEL=cloudimg-rootfs /  ext4 defaults,discard  0 1
fs-0x0x0x0x.efs.ca-central-1.amazonaws.com:/ /mnt/efs nfs nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 0 0
fs-0x0x0x0x /path/to/private efs _netdev,tls,accesspoint=fsap-11111111111111111 0 0
fs-0x0x0x0x /path/to/files efs _netdev,tls,accesspoint=fsap-22222222222222222 0 0
fs-0x0x0x0x /path/to/temp efs _netdev,tls,accesspoint=fsap-33333333333333333 0 0
```

The main efs mount seems to always work, but one or two of the access point mounts always fail when the machine boots up.  I have two servers configured this way. They both behave the same way, but the access points that fail are not always the same.

```
# /var/log/syslog

Aug 27 19:12:29 prod-app-xxx systemd[1]: Started amazon-efs-mount-watchdog.
Aug 27 19:12:30 prod-app-xxx mount[1372]: Exception in thread Thread-1:
Aug 27 19:12:30 prod-app-xxx mount[1372]: Traceback (most recent call last):
Aug 27 19:12:30 prod-app-xxx mount[1372]:   File "/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Aug 27 19:12:30 prod-app-xxx mount[1372]:     self.run()
Aug 27 19:12:30 prod-app-xxx mount[1372]:   File "/lib/python3.8/threading.py", line 870, in run
Aug 27 19:12:30 prod-app-xxx mount[1372]:     self._target(*self._args, **self._kwargs)
Aug 27 19:12:30 prod-app-xxx mount[1372]:   File "/sbin/mount.efs", line 1042, in poll_tunnel_process
Aug 27 19:12:30 prod-app-xxx mount[1372]:     test_tunnel_process(tunnel_proc, fs_id)
Aug 27 19:12:30 prod-app-xxx mount[1372]:   File "/sbin/mount.efs", line 1032, in test_tunnel_process
Aug 27 19:12:30 prod-app-xxx mount[1372]:     % (tunnel_proc.returncode, out.strip(), err.strip()))
Aug 27 19:12:30 prod-app-xxx mount[1372]: AttributeError: 'NoneType' object has no attribute 'strip'
...
Aug 27 19:14:00 prod-app-xxx systemd[1]: path-to-temp.mount: Mounting timed out. Terminating.
Aug 27 19:14:00 prod-app-xxx systemd[1]: path-to-temp.mount: Mount process exited, code=killed, status=15/TERM
Aug 27 19:14:00 prod-app-xxx systemd[1]: path-to-temp.mount: Failed with result 'timeout'.
Aug 27 19:14:00 prod-app-xxx systemd[1]: Failed to mount /path/to/temp.
```
I'm not sure if the failing mounts are related to the exception or not, but the `amazon-efs-mount-watchdog` does nothing to try to remount the ones that failed on boot.  They stay failed until I manually run `sudo mount -a`.

I've [addded the systemd workaround](https://docs.aws.amazon.com/efs/latest/ug/troubleshooting-efs-mounting.html#automount-fix-multiple-fs), 
```
# /etc/systemd/system/mount-nfs-sequentially.service

[Unit]
Description=Workaround for mounting EFS Access Points sequentially at boot time
After=remote-fs.target

[Service]
Type=oneshot
ExecStart=/bin/mount -av
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```
which seems to wait long enough for the mounts to retry and succeed, but the python exception and timeouts are stilll happening in syslog when i examine it. So it's an effective band aid but doesn't really solve the problem.

My system info: 

```
dpkg --list |grep -Ew ' (nfs-common|stunnel4|openssl|amazon-efs-utils|python3) '
ii  amazon-efs-utils                   1.31.1                                     all          This package provides utilities for simplifying the use of EFS file systems
ii  nfs-common                         1:1.3.4-2.5ubuntu3.3                       amd64        NFS support files common to client and server
ii  openssl                            1.1.1f-1ubuntu2.8                          amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  python3                            3.8.2-0ubuntu2                             amd64        interactive high-level object-oriented language (default python3 version)
ii  stunnel4                           3:5.56-1                                   amd64        Universal SSL tunnel for network daemons


$ pip freeze|grep boto
boto3==1.9.253
botocore==1.16.19

$ uname -a
Linux prod-app-xxx 5.11.0-1016-aws #17~20.04.1-Ubuntu SMP Thu Aug 12 05:39:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

I'm happy to provide more config detail / feedback / other logs if needed.

**Comment by lshigupt** [comment]
Thanks @dale-c-anderson  for the feedback. We'll have someone take a look as soon as possible :-)

**Comment by Cappuccinuo** [comment]
This is due to a subprocess output issue, should be fixed now.
