### ISSUE TITLE
Cannot mount EFS and getting different errors.

### ISSUE THREAD

**Issue by Abyweinberg** [aws/efs-utils#138]
Hi all, 

Some information about my server's system

1. I'm running **Debian 9.13**
2. installed efs-utils without problem - **amazon-efs-utils 1.33.2**
3. **Python 3.7.3 and Python 2.7.13** (I'm not sure which one efs-utils uses)
4. **botocore - 1.27.29**
5. **OpenSSL 1.1.0**l - 10 Sep 2019
6. **stunnel 5.39** on x86_64-pc-linux-gnu platform
7. **mount from util-linux 2.29.2** (libmount 2.29.2: selinux, btrfs, assert, debug)

My server uses a role with full access to EFS and the policy DescribeAvailabilityZones from EC2; The SG outbound to the EFS through port 2049. 
My EFS has inbound for the server (with NFS protocol) and outbound to the world.

To check this issue, I created a new server (AWS Linux2) with the same SG, and I am role (basically, I used the EC2 template with a new image), and I have experienced the same issues after installing botocore in this machine efs-utils worked. 

Depending on how I'm trying to mount, I'm getting different errors:
The folder `efs` is located at `/mnt, I was at /mnt in the moment I tried to mount.

1. 

```
sudo mount -t efs -o tls fs-ID:/ efs

Traceback (most recent call last):
  File "/sbin/mount.efs", line 3635, in <module>
    main()
  File "/sbin/mount.efs", line 3606, in main
    config, fs_id, options
  File "/sbin/mount.efs", line 2319, in get_dns_name_and_fallback_mount_target_ip_address
    config, options, fs_id, dns_name
  File "/sbin/mount.efs", line 2352, in get_fallback_mount_target_ip_address
    config, options, fs_id
  File "/sbin/mount.efs", line 2450, in get_fallback_mount_target_ip_address_helper
    mount_target = get_mount_target_in_az(efs_client, ec2_client, fs_id, az_name)
  File "/sbin/mount.efs", line 3413, in get_mount_target_in_az
    az_id = get_az_id_by_az_name(ec2_client, az_name)
  File "/sbin/mount.efs", line 3331, in get_az_id_by_az_name
    az_id = az_info["AvailabilityZones"][0]["ZoneId"]
**KeyError: 'ZoneId'**
```
2. 
```
sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-ID.efs.eu-west-1.amazonaws.com:/ /mnt/efs

mount.nfs4: **Failed to resolve server fs-ID.efs.eu-west-1.amazonaws.com**: Name or service not known
```
3.
```
sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 10.0.132.33:/ /mnt/efs
mount.nfs4: **access denied by server** while mounting 10.0.132.33:/
```

Thank you very much in advance.

**Comment by Abyweinberg** [comment]
Ok, my problem was my DNS server (DC Windowns).
The only way to mount it is using the private IP and removing the policy attached to the EFS.
