### ISSUE TITLE
Watchdog fails to handle invalid entries in /proc/mounts file 

### ISSUE THREAD

**Issue by resios** [aws/efs-utils#150]
It appears that the watchdog process crashes if the `/proc/mounts` file contains an invalid formatted line.

```
/usr/bin/amazon-efs-mount-watchdog
Traceback (most recent call last):
  File "/usr/bin/amazon-efs-mount-watchdog", line 1918, in <module>
    main()
  File "/usr/bin/amazon-efs-mount-watchdog", line 1908, in main
    unmount_count_for_consistency,
  File "/usr/bin/amazon-efs-mount-watchdog", line 881, in check_efs_mounts
    nfs_mounts = get_current_local_nfs_mounts()
  File "/usr/bin/amazon-efs-mount-watchdog", line 652, in get_current_local_nfs_mounts
    mounts.append(Mount._make(mount.strip().split()))
  File "/usr/lib64/python3.7/collections/__init__.py", line 407, in _make
    raise TypeError(f'Expected {num_fields} arguments, got {len(result)}')
TypeError: Expected 6 arguments, got 5
```

The contents of the `/proc/mounts` file has an invalid `/` entry, which only has 5 fields instead of 6 (as per the [documentation](https://man7.org/linux/man-pages/man5/fstab.5.html))

``` 
 / overlay rw,relatime,lowerdir=/container/internal-8f5ee380df9048be873b02b5da448603-4215069314/rootfs,upperdir=/volume/_containers/internal-8f5ee380df9048be873b02b5da448603-4215069314/upperdir,workdir=/volume/_containers/internal-8f5ee380df9048be873b02b5da448603-4215069314/workdir 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev tmpfs rw,nosuid,size=65536k,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666 0 0
shm /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /sys/fs/cgroup tmpfs rw,nosuid,nodev,noexec,relatime,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
/dev/vdg /efs-vols/mde-efs-cache-volume ext4 rw,relatime,data=ordered 0 0
/dev/vdg /etc/hostname ext4 rw,relatime,data=ordered 0 0
/dev/vdg /etc/resolv.conf ext4 rw,relatime,data=ordered 0 0
/dev/vdg /etc/hosts ext4 rw,relatime,data=ordered 0 0
127.0.0.1:/ /efs-vols/efs-cache-volume nfs4 rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,port=20051,timeo=600,retrans=2,sec=sys,clientaddr=127.0.0.1,local_lock=none,addr=127.0.0.1 0 0
```

Other linux commands that parse this file seem to handle this gracefully:

```
pwd
/
df -h .
Filesystem      Size  Used Avail Use% Mounted on
-                20G  5.0G   14G  27% /
```

```
mount: /proc/self/mountinfo: parse error at line 1 -- ignored
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory,release_agent=/proc/1020/root//vaptmde7209_payload.sh)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
/dev/vdg on /efs-vols/mde-efs-cache-volume type ext4 (rw,relatime,data=ordered)
/dev/vdg on /etc/hostname type ext4 (rw,relatime,data=ordered)
/dev/vdg on /etc/resolv.conf type ext4 (rw,relatime,data=ordered)
/dev/vdg on /etc/hosts type ext4 (rw,relatime,data=ordered)
127.0.0.1:/ on /efs-vols/mde-efs-cache-volume type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,port=20051,timeo=600,retrans=2,sec=sys,clientaddr=127.0.0.1,local_lock=none,addr=127.0.0.1)
```

I think the watchdog should handle this situation and skip over any mounts that are malformed.
The code to be modified is [here](https://github.com/aws/efs-utils/blob/master/src/watchdog/__init__.py#L661) and I'll prepare a PR.

**Comment by resios** [comment]
Created a PR for this: https://github.com/aws/efs-utils/pull/151

**Comment by RyanStan** [comment]
The PR above merged.
