### ISSUE TITLE
No such file or directory: '/sbin/status' on Debian 11

### ISSUE THREAD

**Issue by john-ousey** [aws/efs-utils#172]
I see that the efs-utils package has not been verified against Debian 11.

When running mount seeing FileNotFoundError: [Errno 2] No such file or directory: '/sbin/status'

```
❯ mount -t efs -o tls,mounttargetip=12.345.67.89 fs-09f81580f0ef40934 /mnt/mymountpoint
Traceback (most recent call last):
  File "/sbin/mount.efs", line 3811, in <module>
    main()
  File "/sbin/mount.efs", line 3789, in main
    mount_tls(
  File "/sbin/mount.efs", line 2920, in mount_tls
    with bootstrap_tls(
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/sbin/mount.efs", line 1629, in bootstrap_tls
    start_watchdog(init_system)
  File "/sbin/mount.efs", line 1461, in start_watchdog
    proc = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/sbin/status'
```

Is efs-utils support for Debian 11 on the roadmap?

**Comment by john-ousey** [comment]
Support for Debian 11 was no longer needed
