### ISSUE TITLE
Problems running efs-utils with Python3

### ISSUE THREAD

**Issue by glaubitz** [aws/efs-utils#24]
I have packaged ```efs-utils``` for openSUSE and SLE and patched the default Python interpreter to be Python3.

Unfortunately, trying to run ```mount.efs``` on Python3 fails with an error:

```
ip-XXX-XXX-XXX-XXX:~ # python3 /sbin/mount.efs
Traceback (most recent call last):
  File "/sbin/mount.efs", line 674, in <module>
    main()
  File "/sbin/mount.efs", line 654, in main
    config = read_config()
  File "/sbin/mount.efs", line 520, in read_config
    p = ConfigParser.SafeConfigParser()
AttributeError: type object 'ConfigParser' has no attribute 'SafeConfigParser'
ip-XXX-XXX-XXX-XXX:~ #
```

Is Python3 supposed to work or is ```efs-utils``` currently Python2 only?

**Comment by patelia** [comment]
Thanks for finding this glaubitz. It looks like rjschwei has worked on fixing this in [PR #25](https://github.com/aws/efs-utils/pull/25), but I will leave this issue open until we can get those changes approved and merged.

**Comment by Cappuccinuo** [comment]
[New release](https://github.com/aws/efs-utils/releases/tag/1.15)

**Comment by glaubitz** [comment]
Is it certain this issue has been fixed?

I'm still seeing errors regarding ```ConfigParser``` when trying to run the testsuite:

```
[   32s] ============================= test session starts ==============================
[   32s] platform linux -- Python 3.7.3, pytest-5.2.4, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
[   32s] cachedir: .pytest_cache
[   32s] metadata: {'Python': '3.7.3', 'Platform': 'Linux-5.3.12-1-default-x86_64-with-glibc2.2.5', 'Packages': {'pytest': '5.2.4', 'py': '1.8.0', 'pluggy': '0.13.0'}, 'Plugins': {'cov': '2.8.1', 'metadata': '1.7.0', 'mock': '1.11.2', 'html': '1.19.0'}}
[   32s] rootdir: /home/abuild/rpmbuild/BUILD/efs-utils-1.15, inifile: setup.cfg
[   32s] plugins: cov-2.8.1, metadata-1.7.0, mock-1.11.2, html-1.19.0
[   33s] collecting ... collected 95 items / 4 errors / 91 selected
[   33s] 
[   33s] ==================================== ERRORS ====================================
[   33s] _________ ERROR collecting test/mount_efs_test/test_choose_tls_port.py _________
[   33s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/efs-utils-1.15/test/mount_efs_test/test_choose_tls_port.py'.
[   33s] Hint: make sure your test modules/packages have valid Python names.
[   33s] Traceback:
[   33s] test/mount_efs_test/test_choose_tls_port.py:10: in <module>
[   33s]     import ConfigParser
[   33s] E   ModuleNotFoundError: No module named 'ConfigParser'
[   33s] ___________ ERROR collecting test/mount_efs_test/test_get_region.py ____________
[   33s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/efs-utils-1.15/test/mount_efs_test/test_get_region.py'.
[   33s] Hint: make sure your test modules/packages have valid Python names.
[   33s] Traceback:
[   33s] test/mount_efs_test/test_get_region.py:14: in <module>
[   33s]     from urllib2 import URLError
[   33s] E   ModuleNotFoundError: No module named 'urllib2'
[   33s] _________ ERROR collecting test/mount_efs_test/test_is_ocsp_enabled.py _________
[   33s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/efs-utils-1.15/test/mount_efs_test/test_is_ocsp_enabled.py'.
[   33s] Hint: make sure your test modules/packages have valid Python names.
[   33s] Traceback:
[   33s] test/mount_efs_test/test_is_ocsp_enabled.py:10: in <module>
[   33s]     import ConfigParser
[   33s] E   ModuleNotFoundError: No module named 'ConfigParser'
[   33s] ____ ERROR collecting test/mount_efs_test/test_write_stunnel_config_file.py ____
[   33s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/efs-utils-1.15/test/mount_efs_test/test_write_stunnel_config_file.py'.
[   33s] Hint: make sure your test modules/packages have valid Python names.
[   33s] Traceback:
[   33s] test/mount_efs_test/test_write_stunnel_config_file.py:10: in <module>
[   33s]     import ConfigParser
[   33s] E   ModuleNotFoundError: No module named 'ConfigParser'
[   33s] =============================== warnings summary ===============================
[   33s] src/mount_efs/__init__.py:74
[   33s]   /home/abuild/rpmbuild/BUILD/efs-utils-1.15/src/mount_efs/__init__.py:74: DeprecationWarning: invalid escape sequence \.
[   33s]     EFS_FQDN_RE = re.compile('^(?P<fs_id>fs-[0-9a-f]+)\.efs\.(?P<region>[a-z0-9-]+)\.amazonaws.com$')
[   33s] 
[   33s] -- Docs: https://docs.pytest.org/en/latest/warnings.html
[   33s] - generated html file: /home/abuild/rpmbuild/BUILD/efs-utils-1.15/build/pytest/index.html -
[   33s] 
[   33s] ----------- coverage: platform linux, python 3.7.3-final-0 -----------
[   33s] Coverage HTML written to dir build/coverage
[   33s] 
[   33s] FAIL Required test coverage of 80% not reached. Total coverage: 18.90%
[   33s] !!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!
[   33s] ========================= 1 warnings, 4 error in 1.11s =========================
[   33s] make: *** [Makefile:69: test] Error 2
```

**Comment by Cappuccinuo** [comment]
Thank you for the quick follow up. Can you share your linux distribution, kernel version, and python3 version?

**Comment by Cappuccinuo** [comment]
We will push the tests fix now.

**Comment by glaubitz** [comment]
This is on openSUSE Tumbleweed (rolling release), Python 3.7.3, Kernel 5.3.12.

**Comment by Cappuccinuo** [comment]
Could you please try [this new release](https://github.com/aws/efs-utils/releases/tag/v1.16), thanks.

**Comment by glaubitz** [comment]
Yes, this has fixed this particular issue. But the testsuite is still failing for me with other problems:

```
[    5s] =================================== FAILURES ===================================
[    5s] ________________ test_get_dns_name_bad_format_wrong_specifiers _________________
[    5s] 
[    5s] mocker = <pytest_mock.plugin.MockFixture object at 0x7ff4f29746a0>
[    5s] 
[    5s]     def test_get_dns_name_bad_format_wrong_specifiers(mocker):
[    5s]         config = _get_mock_config('{foo}.efs.{bar}')
[    5s]     
[    5s]         with pytest.raises(ValueError) as ex:
[    5s]             mount_efs.get_dns_name(config, FS_ID)
[    5s]     
[    5s] >       assert 'must include' in str(ex)
[    5s] E       AssertionError: assert 'must include' in '<ExceptionInfo ValueError tblen=2>'
[    5s] E        +  where '<ExceptionInfo ValueError tblen=2>' = str(<ExceptionInfo ValueError tblen=2>)
[    5s] 
[    5s] test/mount_efs_test/test_get_dns_name.py:66: AssertionError
[    5s] ______________ test_get_dns_name_bad_format_too_many_specifiers_1 ______________
[    5s] 
[    5s] mocker = <pytest_mock.plugin.MockFixture object at 0x7ff4f28fb518>
[    5s] 
[    5s]     def test_get_dns_name_bad_format_too_many_specifiers_1(mocker):
[    5s]         config = _get_mock_config('{fs_id}.efs.{foo}')
[    5s]     
[    5s]         with pytest.raises(ValueError) as ex:
[    5s]             mount_efs.get_dns_name(config, FS_ID)
[    5s]     
[    5s] >       assert 'incorrect number' in str(ex)
[    5s] E       AssertionError: assert 'incorrect number' in '<ExceptionInfo ValueError tblen=3>'
[    5s] E        +  where '<ExceptionInfo ValueError tblen=3>' = str(<ExceptionInfo ValueError tblen=3>)
[    5s] 
[    5s] test/mount_efs_test/test_get_dns_name.py:75: AssertionError
[    5s] ______________ test_get_dns_name_bad_format_too_many_specifiers_2 ______________
[    5s] 
[    5s] mocker = <pytest_mock.plugin.MockFixture object at 0x7ff4f2998d30>
[    5s] 
[    5s]     def test_get_dns_name_bad_format_too_many_specifiers_2(mocker):
[    5s]         config = _get_mock_config('{fs_id}.efs.{region}.{foo}')
[    5s]     
[    5s]         with pytest.raises(ValueError) as ex:
[    5s]             mount_efs.get_dns_name(config, FS_ID)
[    5s]     
[    5s] >       assert 'incorrect number' in str(ex)
[    5s] E       AssertionError: assert 'incorrect number' in '<ExceptionInfo ValueError tblen=3>'
[    5s] E        +  where '<ExceptionInfo ValueError tblen=3>' = str(<ExceptionInfo ValueError tblen=3>)
[    5s] 
[    5s] test/mount_efs_test/test_get_dns_name.py:84: AssertionError
[    5s] ________________________________ test_main_tls _________________________________
[    5s] 
[    5s] mocker = <pytest_mock.plugin.MockFixture object at 0x7ff4f2954a58>
[    5s] 
[    5s]     def test_main_tls(mocker):
[    5s] >       _test_main(mocker, tls=True)
[    5s] 
[    5s] test/mount_efs_test/test_main.py:52: 
[    5s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[    5s] test/mount_efs_test/test_main.py:38: in _test_main
[    5s]     mount_efs.main()
[    5s] src/mount_efs/__init__.py:740: in main
[    5s]     check_network_status(fs_id, init_system)
[    5s] src/mount_efs/__init__.py:409: in check_network_status
[    5s]     exit_code=0)
[    5s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[    5s] 
[    5s] user_message = 'Failed to mount fs-deadbeef because the network was not yet available, add "_netdev" to your mount options'
[    5s] log_message = 'Failed to mount fs-deadbeef because the network was not yet available, add "_netdev" to your mount options'
[    5s] exit_code = 0
[    5s] 
[    5s]     def fatal_error(user_message, log_message=None, exit_code=1):
[    5s]         if log_message is None:
[    5s]             log_message = user_message
[    5s]     
[    5s]         sys.stderr.write('%s\n' % user_message)
[    5s]         logging.error(log_message)
[    5s] >       sys.exit(exit_code)
[    5s] E       SystemExit: 0
[    5s] 
[    5s] src/mount_efs/__init__.py:126: SystemExit
[    5s] ----------------------------- Captured stderr call -----------------------------
[    5s] Failed to mount fs-deadbeef because the network was not yet available, add "_netdev" to your mount options
[    5s] ------------------------------ Captured log call -------------------------------
[    5s] ERROR    root:__init__.py:125 Failed to mount fs-deadbeef because the network was not yet available, add "_netdev" to your mount options
[    5s] _______________________________ test_main_no_tls _______________________________
[    5s] 
[    5s] mocker = <pytest_mock.plugin.MockFixture object at 0x7ff4f28fbf98>
[    5s] 
[    5s]     def test_main_no_tls(mocker):
[    5s] >       _test_main(mocker, tls=False)
[    5s] 
[    5s] test/mount_efs_test/test_main.py:56: 
[    5s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[    5s] test/mount_efs_test/test_main.py:38: in _test_main
[    5s]     mount_efs.main()
[    5s] src/mount_efs/__init__.py:740: in main
[    5s]     check_network_status(fs_id, init_system)
[    5s] src/mount_efs/__init__.py:409: in check_network_status
[    5s]     exit_code=0)
[    5s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[    5s] 
[    5s] user_message = 'Failed to mount fs-deadbeef because the network was not yet available, add "_netdev" to your mount options'
[    5s] log_message = 'Failed to mount fs-deadbeef because the network was not yet available, add "_netdev" to your mount options'
[    5s] exit_code = 0
[    5s] 
[    5s]     def fatal_error(user_message, log_message=None, exit_code=1):
[    5s]         if log_message is None:
[    5s]             log_message = user_message
[    5s]     
[    5s]         sys.stderr.write('%s\n' % user_message)
[    5s]         logging.error(log_message)
[    5s] >       sys.exit(exit_code)
[    5s] E       SystemExit: 0
[    5s] 
[    5s] src/mount_efs/__init__.py:126: SystemExit
[    5s] ----------------------------- Captured stderr call -----------------------------
[    5s] Failed to mount fs-deadbeef because the network was not yet available, add "_netdev" to your mount options
[    5s] ------------------------------ Captured log call -------------------------------
[    5s] ERROR    root:__init__.py:125 Failed to mount fs-deadbeef because the network was not yet available, add "_netdev" to your mount options
[    5s] =============================== warnings summary ===============================
[    5s] src/mount_efs/__init__.py:74
[    5s]   /home/abuild/rpmbuild/BUILD/efs-utils-1.16/src/mount_efs/__init__.py:74: DeprecationWarning: invalid escape sequence \.
[    5s]     EFS_FQDN_RE = re.compile('^(?P<fs_id>fs-[0-9a-f]+)\.efs\.(?P<region>[a-z0-9-]+)\.amazonaws.com$')
[    5s] 
[    5s] test/mount_efs_test/test_check_unsupported_options.py::test_cafile_unsupported
[    5s] test/mount_efs_test/test_check_unsupported_options.py::test_capath_unsupported
[    5s]   /home/abuild/rpmbuild/BUILD/efs-utils-1.16/src/mount_efs/__init__.py:722: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
[    5s]     logging.warn(warn_message)
[    5s] 
[    5s] test/mount_efs_test/test_is_stunnel_option_supported.py::test_unsupported_option
[    5s]   /home/abuild/rpmbuild/BUILD/efs-utils-1.16/src/mount_efs/__init__.py:263: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
[    5s]     logging.warn('stunnel does not support "%s"', stunnel_option_name)
[    5s] 
[    5s] test/watchdog_test/test_check_child_procs.py::test_child_procs
[    5s]   /home/abuild/rpmbuild/BUILD/efs-utils-1.16/src/watchdog/__init__.py:259: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
[    5s]     logging.warn('Child TLS tunnel process %d has exited, returncode=%d', proc.pid, proc.returncode)
[    5s] 
[    5s] test/watchdog_test/test_check_efs_mounts.py::test_tls_not_running
[    5s]   /home/abuild/rpmbuild/BUILD/efs-utils-1.16/src/watchdog/__init__.py:251: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
[    5s]     logging.warn('TLS tunnel for %s is not running', state_file)
[    5s] 
[    5s] -- Docs: https://docs.pytest.org/en/latest/warnings.html
[    5s] - generated html file: /home/abuild/rpmbuild/BUILD/efs-utils-1.16/build/pytest/index.html -
[    5s] 
[    5s] ----------- coverage: platform linux, python 3.7.3-final-0 -----------
[    5s] Coverage HTML written to dir build/coverage
[    5s] 
[    5s] Required test coverage of 80% reached. Total coverage: 82.83%
[    5s] ================== 5 failed, 124 passed, 6 warnings in 1.56s ===================
```

**Comment by maxbecke** [comment]
@glaubitz thank you for your help with this release. I am going to revert the following 2 commits, delete the v1.15/v1.16 tags, and start over with the Python 3 support. We will pick up with v1.17 for the next tag.

880da73a3773aa269cec5a56e0c479300f4e3582
b6b0d9933dff38196b908318b9d940f657dbe7b0

Furthermore, we've identified the gaps in our process that lead to these issues, and they will be addressed before we do the v1.17 release.

**Comment by glaubitz** [comment]
@maxbecke Thanks a lot for your efforts and I'm very glad I could help!

Even though I think it shouldn't be necessary to remove the 1.15/1.16 tags when you are fixing the issues with 1.17. I have already submitted a 1.16 package in openSUSE now and will wait for the 1.17 release and just update the package in openSUSE.

**Comment by Cappuccinuo** [comment]
Could you please try this [new release v1.17](https://github.com/aws/efs-utils/releases/tag/v1.17), thanks.
