### ISSUE TITLE
Cryptic error message when openssl binary is missing

### ISSUE THREAD

**Issue by adammw** [aws/efs-utils#41]
```
Traceback (most recent call last):
  File "/sbin/mount.efs", line 1369, in <module>
    main()
  File "/sbin/mount.efs", line 1363, in main
    mount_tls(config, init_system, dns_name, path, fs_id, ap_id, mountpoint, options)
  File "/sbin/mount.efs", line 1295, in mount_tls
    with bootstrap_tls(config, init_system, dns_name, fs_id, ap_id, mountpoint, options) as tunnel_proc:
  File "/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/sbin/mount.efs", line 697, in bootstrap_tls
    base_path=state_file_dir)
  File "/sbin/mount.efs", line 842, in create_certificate
    private_key = check_and_create_private_key(base_path)
  File "/sbin/mount.efs", line 905, in check_and_create_private_key
    do_with_lock(generate_key)
  File "/sbin/mount.efs", line 888, in do_with_lock
    return function()
  File "/sbin/mount.efs", line 901, in generate_key
    subprocess_call(cmd, 'Failed to create private key')
  File "/sbin/mount.efs", line 963, in subprocess_call
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE, close_fds=True)
  File "/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Ideally, script should abort with error telling the user that openssl is required for `tls` option, and how to install it.

**Comment by ncharbon** [comment]
Thanks for the feedback. We’ll have someone take a look and post a more detailed response once we better understand the issue.

**Comment by Cappuccinuo** [comment]
Hey @adammw ,

Thanks for your feedback. 

Could you please share your linux distribution and your efs-utils installation steps? Thanks.

**Comment by adammw** [comment]
The mount helper is running within an Amazon linux Docker container as part of the aws-efs-csi-driver.
See https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/Dockerfile#L20-L21

**Comment by adammw** [comment]
Alternatively the `amazon-efs-utils` package should list openssl as a dependency to be automatically installed?

**Comment by Cappuccinuo** [comment]
I list openssl as a dependency, that should solve this issue. Thanks for reporting that! 

https://github.com/aws/efs-utils/blob/master/dist/amazon-efs-utils.spec#L39
https://github.com/aws/efs-utils/blob/master/dist/amazon-efs-utils.control#L5
