### ISSUE TITLE
Missing options in call to function get_dns_names()

### ISSUE THREAD

**Issue by ryan-hallman** [aws/efs-utils#85]
Traceback (most recent call last):
  File "/sbin/mount.efs", line 2174, in <module>
    main()
  File "/sbin/mount.efs", line 2152, in main
    fs_id, path, mountpoint, options = parse_arguments(config)
  File "/sbin/mount.efs", line 1193, in parse_arguments
    fs_id, path = match_device(config, fsname)
  File "/sbin/mount.efs", line 1699, in match_device
    expected_dns_name = get_dns_name(config, fs_id)
TypeError: get_dns_name() missing 1 required positional argument: 'options'

**Comment by wangnyue** [comment]
Thanks for the feedback. We’ll have someone take a look.

**Comment by Cappuccinuo** [comment]
Can you try to mount with `fs-id` first and see if there is any issue? We will fix this soon
